### PR TITLE
add drop=F to reordering

### PR DESCRIPTION
**Pull request by mkuhn**
Without this change, the heatmap will not work when the user only has one row or one column

### CODE REVIEW

**Comment by talgalili** [comment]
Hey there, I'm planning to merge https://github.com/talgalili/d3heatmap/pull/86 into the package.

Could you verify if your PR adds to it or not?

Thanks!

(sorry for responding 4 years later :D I just took over maintaining the package)

**Comment by mkuhn** [comment]
Thanks for taking this over! I've long forgotten for which project I needed this :) 

Looking at the code in #86, the problems addressed by this PR would still be there. So it would be good if you could also merge it in.

**Comment by talgalili** [comment]
Will do, thanks :)

**Comment by talgalili** [comment]
This PR has conflicts, could you please rebase?

**Comment by mkuhn** [comment]
Should be fine now. Since it's been so long that I used the package I can't test it, but I was able to find the code that needed to be changed in the refactored function

**Comment by talgalili** [comment]
Thanks, it's a bit impossible to review the changes, since it seems to include a lot of changes that were already landed from the recent diff.
Could you maybe start a new pull request instead?!

**Pull request closed without merging**
