### PR TITLE
Added axis positioning options and title

### PR DESCRIPTION
**Pull request by xtmwang**
Added these parameters:
# ' @param xaxis_location Location of the x axis, either "bottom" or "top". Defaults to "bottom".
# ' @param yaxis_location Location of the y axis, either "right" or "left". Defaults to "right".
# ' @param xaxis_title Title text of x axis. Will also replace "Column" in the tooltip.
# ' @param yaxis_title Title text of y axis. Will also replace "Row" in the tooltip.
# ' @param xaxis_title_font_size Font size of x axis title in pixels. Defaults to 14.
# ' @param yaxis_title_font_size Font size of y axis title in pixels. Defaults to 14.

### CODE REVIEW

**Comment by hherrada** [comment]
When do you think this merge will take place? Thank you!

**Comment by xtmwang** [comment]
Hello. It seems that no one is maintaining this repo at the moment so I'm not sure. Perhaps a faster way is to clone and copy paste the files into your own repo.

**Comment by talgalili** [comment]
Hello all,
The person responsible for this repo is Joe Cheng from RStudio. I believe he is quite busy, so it is not surprising it is taking him so long to merge this branch. I believe he'll eventually get to it, but that is only my belief.

I would also like to mention heatmaply, which is an R package for creating interactive cluster heatmaps using plotly. As far as I know, it includes all the features of d3heatmap, plus a few more (handles larger data matrix, allows zooming in from the dendrograms and not just from the matrix grid, allows for categorical variables to be included in the sides).
If you are into interactive cluster heatmaps, I hope you'd consider using (/contributing) to it:
https://github.com/talgalili/heatmaply/

Cheers,
Tal

**Comment by talgalili** [comment]
This seems to have been merged into this PR: https://github.com/talgalili/d3heatmap/pull/86
So I'm closing this PR.
If something is missing, please re-open / send a new PR.

Thanks for your contribution!

**Pull request closed without merging**
