### PR TITLE
Consolidated PR; v0.8.3

### PR DESCRIPTION
**Pull request by klaukh**
### Consolidated PR: Issues and PRs incorporated

___BIG___ hat tips to @mkuhn, @pooranis, @Alanocallaghan, @garthtarr, @xtmwang, and @botanize (and others I'm neglecting... sincere apologies) for examples and inspiration on the various implementations.  All mistakes are mine and not anyone else (until the community gets their hands on this, of course!)

### Info
Version 0.8.3 of `d3heatmap`. Version increments where on my own as I was using my fork and modifications of this package elsewhere. Final merged version should please be >= 0.8.3 to coincide with `imports` and `suggests` in dependent packages I have.

#### Note  
Once all needed tweaks to this PR are resolved and the PR is ready to merge, I'll process an updated README and commit for inclusion just prior to merging.

#### Issues to close: 

\#10 - __Question: how to reproduce "Mike Bostock's Les Misérables Co-occurrence"__: can be done via Shiny with a dropdown
\#19 - __Square blocks__: heatmap sizing can take care of that
\#26 - __Display issues with heatmap generated__: can be addressed by sizing or turning off the grid
\#42 - __symm = TRUE seems working incorrectly__: code looks to cover and no reproduceable example given
\#55 - __Regarding visualization of more than 6000 rows using d3heatmap__: can be addressed by sizing or turning off the grid

#### Resolved Issues:  

\#17 - __Add an option to add a heatmap legend__: as discussed in #50. 
\#24 - __Tooltip shows original values, but colors are scaled__: as noted in the issue, this is the `cellnote_scale` argument. 
\#38 - __Plotting NA values__: can be specified by value and color, using `na.value` and `na.color`.
\#40 - __Add main title and axes labels__: added as `main`, `labRow`, and `labCol`.
\#43 - __tooltip mislabeled when zoom in [Firefox]__: same as #63. 
\#45 - __Add side color panel to indicate groups__: adds RowSideColors and ColSideColors, with automatic and palettized color options. Also adds legend and tooltip capabilities conditional on names and label information being provided alongside the sidecolors. This was a well-documented fixed across several forks and branches.
\#46 - __horizontal axis tick rotation options__: adds the parameter, `srtCol`.
\#50 - __Color key and density info legend__: adds the legend and density info with two options: `histogram` and `none`. 
\#52 - __cexCol and cexRow seem inversed__: corrects for this issue; fairly straightforward fix.
\#53 - __RowSideColors and ColSideColors gives black on invalid color (also alpha)__: corrects for alpha inclusion causing black colors in RowSideColors and ColSideColors. 
\#63 - __Wrong mouseover information shown when zoomed__: a well documented issue, especially with Firefox. Corrects for this 
\#71 - __Change name of column and row in the tooltip__: includes `cellnote_row`, `cellnote_col`, and `cellnote_val` to allow for customization of tooltip
\#74 - __Print Cell Labels in Heatmap__: includes `print.values = TRUE` argument. 
\#77 - __d3heatmap does not render in flexdashboard when scatterD3 also used__: changed all `d3` to `d3v3` to preempt conflicts with _d3v4_.
\#81 - __specify that zero values get neutral color in diverging data__: `symbreaks = TRUE` argument available.
\#83 - __x must be numeric probelm in d3heatmap shiny__: filters non-numeric columns at initial d3heatmap call, from either data.frame or matrix.
\#84 - __Consolidated PR and CRAN update (sister issue to this PR)__: CRAN check successful and devtools spellcheck processed and remedied.

### PRs

\#21 - __typo__: corrected in some commit long ago.
\#31 - __Implement ColSideColors/RowSideColors__: implemented as in the PR, with some modification.
\#35 - __minVal and maxVal options__: implemented as in the PR, with some modification.
\#58 - __Add optional parameters: fix the range of the input data, NA color__: implemented as in the PR, with some modification.
\#68 - __Fix self.getId error__: implemented as in the PR.
\#72 - __Added axis positioning options and title__: implemented as in the PR, with some modification.
\#75 - __Replace ordinal scales with linear scales__: implemented as in the PR.

#### API

Inspired by _dygraphs_ and able to leverage _magrittr_, the new API provides a second method for invoking d3heatmap and integrating with Shiny apps, modules, and gadgets! Examples:

    library(d3heatmap)
    library(magrittr)
    
    d3heatmap(mtcars, dendrogram = 'none', key = TRUE, col = 'RdYlGn',
              scale = 'column', key.title = "Legend", print.values = T,
              notecol = 'white') %>% 
      hmAxis("x", title = "test", location = 'bottom') %>% 
      hmAxis("y", title = "test", location = 'left') %>% 
      hmCells(font.size = 8, color = 'blue') %>% 
      hmLegend(show = T, title = "Title", location = "tl")
  

#### Gadget

An shiny gadget coupled with an `S4` class that has `print()` and `save()` methods. Gadget takes normal `d3heatmap` inputs and allows for interactive adjustment of the heatmap. Gadget allows for filtering rows and columns, and also a dynamic filter to interactively subset the entire underlying data set. Saving the gadget to an object generates the `S4` class that contains the heatmap, data, filter, and settings.  Passing the gadget back into the function `d3heatmapGadget(gadget)` starts the user at the last state of the gadget.

    gadget <- d3heatmapGadget(mtcars, col = 'blues')
		print(gadget)
		save(gadget, file = "heatmap.html")
    gadget <- d3heatmapGadget(gadget)
	

Note: this PR was edited for grammar and spelling

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
Great to see, thanks for this @klaukh! I did some work on my fork recently, though from the sounds of it this PR might already contain most of it

**Comment by klaukh** [comment]
@Alanocallaghan, thanks! And double thanks for the work you did on your fork, as much of it directly influenced stuff in this PR. If you see additional things that can be tweaked or added, feel free to offer some code snippets here or even an issue or PR over in my fork and work to I'll incorporate.

**Comment by pooranis** [comment]
@klaukh Thanks for the mention!  And thanks for writing this package.  Back when I made those commits, I knew very little js and nothing about d3.  I learned a lot reading your (well-written) code.

**Comment by klaukh** [comment]
Thanks, but only the bad stuff is mine... the good code is undoubtedly something I got from someone else. Please let me know if something needs to be tweaked.

**Comment by vyster** [comment]
Hello, I need to make https://bost.ocks.org/mike/miserables/ this from the co-occurrence matrix I have generated., Can you help??

**Comment by vyster** [comment]
Hello, I need to make https://bost.ocks.org/mike/miserables/ this from the co-occurrence matrix I have generated., Can you help??
https://drive.google.com/file/d/1c275QvW7XjY5llhBvExSn_XWgK5w7o2R/view?usp=sharing

**Comment by talgalili** [comment]
Hey @klaukh :)
I've now take ownership over the repo from Joe and RStudio.
I see you've put a lot of work here (~3 years ago, but still).

Do you think I should merge it as is? Do you want to add more features/changes before I do so?

Do you know if there are other PR I should include/omit, given this PR?

Thanks,
T

**Comment by klaukh** [comment]
@talgalili As you can probably infer I haven't looked at this in years. I recommend you proceed as you see fit

**Comment by talgalili** [comment]
Fair enough. :)

**Pull request merged**
